name: Tests

on: [push, pull_request]

jobs:
    lowest_dependencies:
        name: PHP 8.0 tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v1
              with:
                  php-version: 7.1
                  coverage: none

            - run: composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable
            - run: vendor/bin/tester tests -s -C
